//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailBodyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailBodyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Properties.EmailBodyResources", typeof(EmailBodyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement of Online Auction System.
        /// </summary>
        public static string AnnouncementSystem {
            get {
                return ResourceManager.GetString("AnnouncementSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4 style=&apos;color:green;&apos;&gt;Your auction product has been approved&lt;/h4&gt;
        ///&lt;p&gt;&lt;strong&gt;Product information&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Product&apos;s name:&lt;/strong&gt; {0}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Category:&lt;/strong&gt; {1}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Init price:&lt;/strong&gt; {2}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Step price:&lt;/strong&gt; {3}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Date approve:&lt;/strong&gt; {4}&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;Sincerely thank you.&lt;/p&gt;.
        /// </summary>
        public static string EmailApproveProduct {
            get {
                return ResourceManager.GetString("EmailApproveProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4 style=&apos;color:red;&apos;&gt;We regret to inform you that you did not win the auction&lt;/h4&gt;
        ///&lt;p&gt;&lt;strong&gt;Auction information&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Product&apos;s name:&lt;/strong&gt; {0}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Category:&lt;/strong&gt; {1}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Auction Type:&lt;/strong&gt; {2}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Highest price:&lt;/strong&gt; {3}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Your price:&lt;/strong&gt; {4}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Start time:&lt;/strong&gt; {5}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;End time:&lt;/strong&gt; {6}&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;To view auction details, you can log into the system, go to the auction history [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailFailedAuction {
            get {
                return ResourceManager.GetString("EmailFailedAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4 style=&apos;color:green;&apos;&gt;Your order has been processed successfully.&lt;/h4&gt;
        ///&lt;p&gt;&lt;strong&gt;Your order information&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Product&apos;s name:&lt;/strong&gt; {0}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;FirstName:&lt;/strong&gt; {1}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;LastName:&lt;/strong&gt; {2}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Date payment:&lt;/strong&gt; {3}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Shiping Address:&lt;/strong&gt; {4}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Telephone:&lt;/strong&gt; {5}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;OrderType:&lt;/strong&gt; {6}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Product Price:&lt;/strong&gt; {7}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Shipping:&lt;/strong&gt; Free&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;T [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailPaymentSuccessToBidder {
            get {
                return ResourceManager.GetString("EmailPaymentSuccessToBidder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4 style=&apos;color:green;&apos;&gt;Your price is not the highest price&lt;/h4&gt;
        ///&lt;p&gt;&lt;strong&gt;Auction information&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Product&apos;s name:&lt;/strong&gt; {0}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Category:&lt;/strong&gt; {1}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Highest price:&lt;/strong&gt; {2}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Your price:&lt;/strong&gt; {3}&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;To view auction details, you can log into the system, go to the auction section.&lt;/p&gt;
        ///&lt;p&gt;Sincerely thank you.&lt;/p&gt;.
        /// </summary>
        public static string EmailPriceNotHighest {
            get {
                return ResourceManager.GetString("EmailPriceNotHighest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4 style=&apos;color:red;&apos;&gt;Your auction product has been rejected&lt;/h4&gt;
        ///&lt;p&gt;&lt;strong&gt;Product information&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Product&apos;s name:&lt;/strong&gt; {0}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Category:&lt;/strong&gt; {1}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Init price:&lt;/strong&gt; {2}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Step price:&lt;/strong&gt; {3}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Date reject:&lt;/strong&gt; {4}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Reason reject:&lt;/strong&gt; {5}&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;Sincerely thank you.&lt;/p&gt;.
        /// </summary>
        public static string EmailRejectProduct {
            get {
                return ResourceManager.GetString("EmailRejectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4 style=&apos;color:green;&apos;&gt;We congratulate you on a successful auction&lt;/h4&gt;
        ///&lt;p&gt;&lt;strong&gt;Auction information&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Product&apos;s name:&lt;/strong&gt; {0}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Category:&lt;/strong&gt; {1}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Auction Type:&lt;/strong&gt; {2}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Highest price:&lt;/strong&gt; {3}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Your price:&lt;/strong&gt; {4}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Start time:&lt;/strong&gt; {5}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;End time:&lt;/strong&gt; {6}&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;To view auction details, you can log into the system, go to the auction history section.&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailSuccessAuction {
            get {
                return ResourceManager.GetString("EmailSuccessAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4 style=&apos;color:green;&apos;&gt;Your product has been successfully auctioned and sold.&lt;/h4&gt;
        ///&lt;p&gt;&lt;strong&gt;Your product information&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Product&apos;s name:&lt;/strong&gt; {0}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Price:&lt;/strong&gt; {1}&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Date sold:&lt;/strong&gt; {2}&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;To view auction details, you can log into the system, go to the auction history section.&lt;/p&gt;
        ///&lt;p&gt;Sincerely thank you.&lt;/p&gt;.
        /// </summary>
        public static string EmailSuccessPaymentToAuctioneer {
            get {
                return ResourceManager.GetString("EmailSuccessPaymentToAuctioneer", resourceCulture);
            }
        }
    }
}
